FROM node:20.9.0 AS build-img
WORKDIR /app

COPY /frontend/package.json .
RUN npm install --force
COPY /frontend/ .
RUN npm run build --prod

# Stage 2: Serve the Angular app using Nginx
FROM nginx:alpine

COPY --from=build-img app/dist/frontend /usr/share/nginx/html
COPY --from=build-img app/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 4200
CMD ["nginx", "-g", "daemon off;"]
