services:
  postgres:
    image: postgres
    container_name: ${POSTGRES_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - network

#  ollama:
#    image: ollama/ollama
#    container_name: ${POSTGRES_NAME}
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: ${POSTGRES_DB}
#    networks:
#      - network

  server:
    build:
      context: .
      dockerfile: backend/server/dockerfile
    container_name: ${SERVER_NAME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    networks:
      - network


#  server:
#    container_name: ${WHISPER_NAME}
#    build:
#      context: .
#      dockerfile: backend/server/dockerfile
#    ports:
#      - "8001:8000"
#    networks:
#      - network

  site:
    container_name: ${SITE_NAME}
    build:
      context: .
      dockerfile: frontend/dockerfile
    ports:
      - "4200:4200"
    networks:
      - network



networks:
  network:
    driver: bridge
