services:
  postgres:
    image: postgres
    container_name: ${POSTGRES_NAME}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - network


  whisper:
    container_name: ${WHISPER_NAME}
    build:
      context: .
      dockerfile: whisper/dockerfile
    ports:
      - "8001:8000"
    networks:
      - network


networks:
  network:
    driver: bridge
