FROM nvidia/cuda:11.8.0-cudnn8-runtime-ubuntu22.04

WORKDIR /whisper

RUN apt-get update && apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && apt-get install -y \
    --no-install-recommends \
    ffmpeg \
    git \
    python3.10 \
    python3-pip


COPY /backend/whisper/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

#RUN python3 -c "from faster_whisper import WhisperModel; model = WhisperModel('deepdml/faster-whisper-large-v3-turbo-ct2')"

COPY /backend/whisper/ .

COPY .env .

CMD ["/bin/bash", "-c", "python3 app.py"]
