FROM python:3.10

WORKDIR /server

RUN apt-get update && apt-get install -y ffmpeg

COPY /backend/server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY /backend/server/ .

COPY .env .

CMD ["/bin/bash", "-c", "python3 app.py"]
