FROM python:3.10

WORKDIR /server

RUN apt-get update && apt-get install -y ffmpeg supervisor

COPY /backend/server/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY /backend/server/ .

COPY .env .

CMD ["/usr/bin/supervisord", "-c", "./supervisord.conf"]
